Vagrant.configure("2") do |config|
 config.vm.provider "virtualbox" do |v|
    v.name = "db_vm"
    end
   config.vm.box = "centos/7"
   config.vm.network "private_network", ip: "192.168.33.100"
 #  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/authorized_key"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = "1"
   end
config.vm.provision :shell, path: "db1_vm.sh"
end
